ACTIVITY_EVENT_ATTEND = 'Attended an Event'
ACTIVITY_EVENT_CREATE = 'Organized an Event'
ACTIVITY_CAMPAIGN = 'Participated in a campaign'
ACTIVITY_MONTH_PLANNING = 'Month planning'
ACTIVITY_MONTH_RECAP = 'Month recap'
ACTIVITY_RECRUITMENT_EFFORT = 'Recruitment effort'

READONLY_ACTIVITIES = [ACTIVITY_CAMPAIGN, ACTIVITY_EVENT_ATTEND,
                       ACTIVITY_EVENT_CREATE]
UNLISTED_ACTIVITIES = [ACTIVITY_EVENT_ATTEND, ACTIVITY_EVENT_CREATE,
                       ACTIVITY_MONTH_PLANNING, ACTIVITY_MONTH_RECAP,
                       ACTIVITY_RECRUITMENT_EFFORT]
